"""UI orchestration boundary for TraceAI Control."""

from .audit_checklist_contract import UI_SCHEMA_VERSION
from .audit_checklist_section_widgets import (
    DEFAULT_DISPLAY_VALUE_LIMIT,
    DEFAULT_TABLE_ROW_LIMIT,
    SectionDisplayModel,
    SectionListItem,
    build_section_display_model,
    build_section_list_items,
    export_section_display_as_text,
    export_section_display_as_tsv,
    find_section_by_key,
    humanize_field_label,
    normalize_tsv_cell,
    rows_to_tsv,
    truncate_display_text,
)
from .audit_checklist_view_model import (
    AuditChecklistUiSection,
    AuditChecklistUiViewModel,
    build_audit_checklist_ui_view_model,
    validate_audit_checklist_ui_payload,
)
from .cli import build_parser, build_request_from_args, main
from .orchestrator import (
    DocxReportGenerator,
    TraceabilityCaseRunner,
    UiGenerationRequest,
    UiGenerationResult,
    generate_report_from_ui_request,
    validate_ui_generation_request,
)
from .visual import (
    VisualAuditChecklistResult,
    build_request_from_form_values,
    format_audit_checklist_preview,
    format_section_display_text,
    run_visual_app,
    submit_audit_checklist_form_values,
    submit_visual_form_values,
    validate_audit_checklist_form_values,
    write_selected_section_tsv,
)

__all__ = [
    "AuditChecklistUiSection",
    "AuditChecklistUiViewModel",
    "DEFAULT_DISPLAY_VALUE_LIMIT",
    "DEFAULT_TABLE_ROW_LIMIT",
    "DocxReportGenerator",
    "SectionDisplayModel",
    "SectionListItem",
    "TraceabilityCaseRunner",
    "UI_SCHEMA_VERSION",
    "UiGenerationRequest",
    "UiGenerationResult",
    "VisualAuditChecklistResult",
    "build_audit_checklist_ui_view_model",
    "build_parser",
    "build_request_from_args",
    "build_request_from_form_values",
    "build_section_display_model",
    "build_section_list_items",
    "export_section_display_as_text",
    "export_section_display_as_tsv",
    "find_section_by_key",
    "format_audit_checklist_preview",
    "format_section_display_text",
    "generate_report_from_ui_request",
    "humanize_field_label",
    "main",
    "normalize_tsv_cell",
    "rows_to_tsv",
    "run_visual_app",
    "submit_audit_checklist_form_values",
    "submit_visual_form_values",
    "truncate_display_text",
    "validate_audit_checklist_form_values",
    "validate_audit_checklist_ui_payload",
    "validate_ui_generation_request",
    "write_selected_section_tsv",
]
